### ISSUE TITLE
Build from source?

### ISSUE THREAD

**Issue by ArianKG** [cryptoAlgorithm/nt5src#5]
How can I build it from source?

**Comment by cryptoAlgorithm** [comment]
As of now, numerous people have tried building this leak from source but failed, due to important libraries and executables missing from the leak. However, if you can source these executables from a compiled windows XP image, (namely winlogon.exe and more drivers iirc), it is possible to compile it into a full working windows XP image.

Please note i didn't leak this source code, i merely am providing a mirror of it on GitHub (as stated on the README). If you'd like to learn more, it might be better to read one of the many articles found online (since they might contain more information than i can provide)
